### ISSUE TITLE
Searching claims by claim code

### ISSUE THREAD

**Issue by tansentim** [openimis/openimis-be-api_fhir_py#45]
Health facilities use the claim code as their primary reference for individual claims.  Other references are by patient and visit dates.

This interface (FHIR STU3) does not allow such searches.

The ClaimViewSet method in the views.py file does not allow searching except by uuid.  As the health facility generally does not see the uuid, using the claim code ('code' in the Claim model) to look for a specific claim by claim code, or by patient, or by service date, or even health facility is not possible.  I note that some of these have been implemented in the r4 interface (however not by claim code).

I believe the following additional method in the class ClaimViewSet would enhance its usefulness.

```
def list(self, request, *args, **kwargs):
    claim_code = request.GET.get(“claim_code”)
    queryset = self.get_queryset()
    if claim_code:
        queryset = queryset.filter(code=claim_code)

    serialiser = ClaimSerializer(self.paginate_queryset(queryset), many=True)
    return self.get_paginated_response(serializer.data)
```

Also the code used in the R4 interface would also be helpful.

**Comment by delcroip** [comment]
Hello @tansentim 

FHIR V3 was missing to many features required by openIMIS, we were obliged to use lots of extension, that is why to deprecated it and moved to FHIRv4.

May I ask in which context do you need the v3 ?

thank in advance.

Best regards

**Comment by tansentim** [comment]
Dear Patrick,

I volunteer with a rural hospital in Nepal.  I am trying to link our systems with the implementation of OpenIMIS by the Nepal Government Health Insurance Board.

The HIB has only given us access to the v3 FHIR interface.

Kind regards,
Tim Nicholson

**Comment by delcroip** [comment]
Thanks for the reply @tansentim

@purusap, will you deploy the FHIR V4 (required for DHIS2 etl) in Nepal ? if yes it might help here.

@tansentim integration of openIMIS with Hospital management system is very important for the community, feel free to ask for a meeting if you think it is required.

Best regards
 
poke @dragos-dobre

**Comment by purusap** [comment]
Hello @tansentim 
HIB is deploying FHIR V4  in the test server. Will update you when its done.

Regards

**Comment by tansentim** [comment]
Dear Patrick,

I was just looking at the FHIRv4 implementation, and am puzzled by one line in the list method of the ClaimViewSet class in openimis-be-api_fhir_r4_py/views.py.

The line is currently line 173 which is
queryset = queryset.filter(identifier=identifier)

The queryset is on the Claim model, but I cannot see an ‘identifier’ field in that model (looking at the Claim class in openimis-be-claim_py/models.py).
I wondered if that was meant to be queryset.filter(code=identifier)?

Best regards,
Tim.

**Comment by dragos-dobre** [comment]
Hi @tansentim,

First, I want to make sure you are looking on the latest developments that contains enhancements and bug fixes. For this, please use the develop branch. 

If you look on the Claim model declaration, you will find the `identifier` field: https://github.com/openimis/openimis-be-api_fhir_py/blob/develop/api_fhir/models/claim.py#L137 . Working with FHIR requires to use FHIR resources, and `code` is not FHIR Claim field (not in the root): https://www.hl7.org/fhir/claim.html. The line you mention is about searching capabilities: https://www.hl7.org/fhir/claim.html#search . 

We will create the openIMIS FHIR R4 IG (documentation) during next months that will hopefully simplify the understanding and implementation of openIMIS FHIR R4 module. 

As you move to FHIR R4 module, I will close this issue here. If you have questions, don't hesitate to contact us. Our official channel for questions and bug reporting is https://openimis.atlassian.net/servicedesk/customer/portals. We would prefer to use this channel or you can join the openIMIS community in Discord (currently in testing): https://discord.gg/J58HAwE6

Best regards,
Dragos
